name: Actions

on:
  push:
    branches:
      - master

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Decrypt configuration file
        run: sh ./.github/scripts/decrypt_secret.sh
        env:
          SECRET_PASSPHRASE: ${{secrets.SECRET_PASSPHRASE}}

      - name: Install PHP dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Install Node.js dependencies
        run: npm install

      - name: Run the test suite
        run: ./vendor/bin/paratest

      - name: Login
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:login

      - name: Push
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:push -a laravel-react-admin web

      - name: Release
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:release -a laravel-react-admin web
